### ISSUE TITLE
Task - Comprehensive collection object - Georeference coordinates

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1327]
The the object is georeferenced, please display the coordinates, both in the map display as well as under georeference blue button. Which is now displayed as "Georeferences (1)". I would like to visually verify that the verbatim coordinates match to the dot coordinates.

**Comment by jlpereira** [comment]
@proceps can you confirm is this is okay now? let me know if you prefer a different message there.

**Comment by mjy** [comment]
This sounds like a general soft validation context/alert, rather than a specific addition to the UI?

Perhaps you can add a soft validation modal when you click the hexagon?

**Comment by jlpereira** [comment]
Done as a long time, reopen if you need something different there

**Comment by proceps** [comment]
I still do not see the coordinates. I would like to see something like: 56.23428; -12.723. Not just pointer in both comprehensive form and in georeference pop up
