### ISSUE TITLE
Strange error message

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1769]
Reference: https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=321786

Brasiliogovea Martens 1960 has been misspelled Brasilogovea by Shear 1977.
So I have created both names (protonyms) and indicated the second as a misspelling of the first.
![image](https://user-images.githubusercontent.com/46284943/94149167-e79d3d00-fe4d-11ea-8233-d8ace318e40f.png)

But I got an orange message:
![image](https://user-images.githubusercontent.com/46284943/94149062-cdfbf580-fe4d-11ea-9e4d-698719bceff0.png)

Then I added Martens 1969 to Shear's misspelling and got a new error message:
![image](https://user-images.githubusercontent.com/46284943/94148987-b3c21780-fe4d-11ea-8ef2-3b4047a4b6c9.png)

**Comment by mjy** [comment]
@proceps Please add what's going on here to taxonworks_doc.  @adrik29 we automatically draw author/year from the properlly spelled name.

**Comment by proceps** [comment]
@adrik29 for the misspelling, you only need source, but you do not need person. The author always comes form the correctly spelled name.

**Comment by adrik29** [comment]
Thanks, Dmitry:
Then the first error message is incorrect?

**Comment by proceps** [comment]
Original publication is missing? Yes it is correct, the source is required for the misspelling.

**Comment by adrik29** [comment]
No, let's use my example above:
Shear 1977 made the misspelling, and he is already cited.
What is lacking that may have caused the message?
Can you go to the URL that I indicated?

**Comment by proceps** [comment]
@adrik29 you need to add me to the project. In the first picture, you posted from the Browse TN: The second protonym does not has a citation. The taxon_name_relationship has a citation. The citation should be on protonym (or both).

**Comment by adrik29** [comment]
Ah, I thought you were already in the project, sorry, I will add you now.

**Comment by adrik29** [comment]
![image](https://user-images.githubusercontent.com/46284943/94169831-aa44a980-fe65-11ea-8df6-991ed33de0a0.png)

**Comment by proceps** [comment]
Yes, sorry, did not check. I fixed it, see the record.

**Comment by adrik29** [comment]
Are we talking about the same record? The error still appears to me:
https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=665526

**Comment by proceps** [comment]
previous message was for
https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=321786
Please see the difference.

**Comment by adrik29** [comment]
Uh, sorry I didn't explain correctly.
The error message is propagating to the species entry.
I'm trying to determine what you did to the genus entry.

**Comment by proceps** [comment]
Delete the author role, and enter the author original source.

**Comment by adrik29** [comment]
AH, I saw you put the incorrect subsequent spelling Brasilogovea with author as Shear, ok I had missed that.

**Comment by adrik29** [comment]
Aaaaaaaaaaaaaaaaaaaahn = got it!
Thanks, Dmitry!

**Comment by proceps** [comment]
In this case it is not the author, it is just a citation for the original source where the protonym is introduced. This is actually the same citation, you can see in the radial annotator for the object. But since it is a misspelling the role is not required. The author string is still determined from the correctly spelled protonym.

**Comment by adrik29** [comment]
Now it is totally clear.
I'm grateful for your attention!!!
