### ISSUE TITLE
Task - New Taxon Name - original combination not set properly

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#206]
When I create a new species and click to set an original combination as current, only species name is positioned properly, the genus name is not set.

**Comment by proceps** [comment]
Subgenus is not created. Please check other ranks. A species relationship should be created if a current one is a subspecies.

**Comment by jlpereira** [comment]
Ops sorry, I thought you was meaning set only the parent. 
Fixed, let me know if you see other issues related with this

**Comment by proceps** [comment]
@jlpereira Still not there for a species group name you may have a name classified as 'Aus (Aus) aus aus'. You have four ranks. Genus, subgenus, species and subspecies. All four should be set up if I use a button to copy current classification.

**Comment by proceps** [comment]
@jlpereira Sorry, I did not pull :)
