### ISSUE TITLE
Pinboard Icon for Source seems to have disappeared in Asserted Distributions Task

### ISSUE THREAD

**Issue by JimWoolley** [SpeciesFileGroup/taxonworks#2380]
See attached screen shot.  Shouldn't the blue pinboard icon for source be in the indicated spot?

UCD, Production Version
Chrome browser
![Screen Shot 2021-08-02 at 9 42 20 AM](https://user-images.githubusercontent.com/30122486/127880506-6367cbcd-f3fe-43ba-a305-1bbd5d0a8499.png)

**Comment by proceps** [comment]
there is also problem in Edit TN, the pinbutton for source is just blue circle

**Comment by proceps** [comment]
in asserted distribution, I believe it is already fixed

**Comment by JimWoolley** [comment]
Still not seeing pinbutton for source in Asserted Distrivbution, Production version of UCD.


Jim Woolley
Professor Emeritus
Department of Entomology
Heep Center MS 2475
Texas A&M University
College Station, TX 77843-2475

**Comment by proceps** [comment]
we just wait for production update
