### ISSUE TITLE
[Bug]: Saving a CO in Comprehensive takes much longer if many COs are assigned to collecting event

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3388]
### Steps to reproduce the bug

```bash
1. When I am in comprehensive and I assign a CO to a CE that has many other COs
2. And the CE is NOT being updated
3. Then saving takes much longer (>2 seconds, seems to scale linearly for number of assigned COs to given CE)
...
```

### Expected behavior

Should only update CE for all COs if the CE is modified within Comprehensive

### Environment

Production

### Version

 v0.32.2

### Browser Used

Chrome

**Comment by mjy** [comment]
Issue is blind cascading update of DwC when CE is saved (even with no changes). 

* [ ] Put a delayed job on for records of a ceratain size
* [ ] Don't trigger if CE doesn't change.

**Comment by mjy** [comment]
@tmcelrath This should be resolved with Delayed jobs?

**Comment by tmcelrath** [comment]
No. Still an issue. Actually still an issue even if CE is not modified at all. Eg I can modify a CO buffered field and save and it takes longer if it’s a CE with lots of COs on it.

**Comment by mjy** [comment]
I think this is maybe resolved now?  All DwC updates are delayed jobs now.
