### ISSUE TITLE
[Bug]: try to add global Q identifier, software says taken, search doesn't find who has this id

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#3445]
### Steps to reproduce the bug

```bash
1. Uniquified instances of G. C. (George Campbell) Eickwort in INHS Insect Collection on Production
2. Then for this person, tried to add his wikidata Q number = Q55030504 as Global unique ID. See this to verify https://www.wikidata.org/wiki/Q55030504
3. Software returned error message saying this identifier "Has already been taken"
4. Tried to search People to figure out who has this identifier assigned using **Filter People** and identifiers, no result.
```

### Screenshot

![taken](https://github.com/SpeciesFileGroup/taxonworks/assets/2990155/a71cb422-c28b-4782-ab74-b24e35a4cfa2)

### Expected behavior

I expect to be able to add a wikidata identifier to a given person.

Other weirdness found. @tmcelrath can verify 

**Trying to use** 
a. Filter People > Matching identifiers (value = Q55030504)
OR 
b. Filter People > Identifiers (where identifier = Q55030504)
doesn't result in a useful hit.

Use case "a" produces this
![WeirdFirstName](https://github.com/SpeciesFileGroup/taxonworks/assets/2990155/f8f4066f-26df-4a7c-b534-24102e4a8b02)

Use case "b" produces no hits

### Environment

Production

### Version

 v0.33.1

### Browser Used

firefox

**Comment by proceps** [comment]
This does not really look as globally unique identifier. 'Q12345' could easily be a collection code. @miy. we should probably change the scope from just cached to cached and type, in case of local identifier: cached, type and project_id.

**Comment by tmcelrath** [comment]
But isn't it in the "Wikidata" special class?

**Comment by mjy** [comment]
@tmcelrath is correct.  The Q is unique per class.

**Comment by mjy** [comment]
Seems like @debpaul managed to add an Identifer to a Person that no longer existed, probably because some UI element was not removed. 

Time to improve validation.

**Comment by mjy** [comment]
@debpaul I think this is resolved, if confirmed please close.

**Comment by debpaul** [comment]
@mjy reopening this ... I still get **has already been taken** and at the time I cannot find the person or other object to which that Q number has been assigned.
